spring:
  profiles:
    active: development
  datasource:
    initial-size: 1
    max-active: 20
    max-idle: 20
    test-while-idle: true
    validation-query: SELECT 1
    url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bebase?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

