spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    mongodb:
      host: localhost

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    mongodb:
      host: localhost

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    mongodb:
      host: localhost

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  data:
    mongodb:
      host: localhost

